apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: test-e-portal-pipeline
description: Deployment pipeline for Test E-Portal API
serialPipeline:
  stages:
    - targetId: test
      profiles: []
      strategy:
        standard:
          verify: false
    - targetId: prod
      profiles: []
      strategy:
        standard:
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: Test environment
run:
  location: projects/test-e-portal-api-service/locations/asia-south2
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Prod environment
requireApproval: true
run:
  location: projects/test-e-portal-api-service/locations/asia-south2